[cache]
enable = true
expiry = 300  # seconds

[plotting]
years_to_plot = 1
indicator_height_ratio = 0.3

[plotting.colors]
# Valid colors: black, red, green, yellow, blue, magenta, cyan, white
# Optional prefix: bright_ (e.g. 'bright_green')
text = "white"
main_line = "blue"
overbought = "red"
oversold = "green"

[moving_averages]
ma_1 = 20
ma_2 = 50
ma_3 = 200

[moving_averages.colors]
ma_1 = "green"
ma_2 = "yellow"
ma_3 = "red"

[bollinger_bands]
period = 20
std_dev = 2

[bollinger_bands.colors]
sma = "yellow"
upper_band = "red"
lower_band = "green"

[macd]
fast_len = 12
slow_len = 26
signal_len = 9

[macd.colors]
signal = "red"
histogram = "green"

[rsi]
period = 14
overbought_level = 70
oversold_level = 30

[mfi]
period = 14
overbought_level = 80
oversold_level = 20

[stochastics]
k_period = 14
k_smoothing = 3  # Set to 1 for fast stochastics
d_period = 3
overbought_level = 80
oversold_level = 20

[stochastics.colors]
k_line = "blue"
d_line = "yellow"

[atr]
period = 14

